### ISSUE TITLE
Raspberrypi 3B+ doesn't boot

### ISSUE THREAD

**Issue by Hains** [PLi-metas/meta-raspberrypi#5]
Raspberrypi 3B+.
Flashed with Etcher 1.4.4.
Up to date image.

platform/fixed: No such file or directory.
MDIO: No such file or directory.
bus.oi/modalias: No such file or directory.

Then black screen forever.

**Comment by milaebrothers** [comment]
I'm tryng to flash my sd for rpi3 I'll let you know

**Comment by persianpros** [comment]
Same for me, 3B+ black screen ...

**Comment by persianpros** [comment]
Fixed: https://github.com/PLi-metas/meta-raspberrypi/commit/812478fd3969d1fa5ed406c5e16f61508b25bc54
